# Generated by Django 6.0.2 on 2026-03-01 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_school_onboarding_complete_school_onboarding_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='tenants.school')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('nursery_1', 'Nursery 1'), ('nursery_2', 'Nursery 2'), ('kindergarten_1', 'Kindergarten 1'), ('kindergarten_2', 'Kindergarten 2'), ('primary_1', 'Primary 1'), ('primary_2', 'Primary 2'), ('primary_3', 'Primary 3'), ('primary_4', 'Primary 4'), ('primary_5', 'Primary 5'), ('primary_6', 'Primary 6'), ('jhs_1', 'JHS 1'), ('jhs_2', 'JHS 2'), ('jhs_3', 'JHS 3'), ('shs_1', 'SHS 1'), ('shs_2', 'SHS 2'), ('shs_3', 'SHS 3'), ('other', 'Other')], max_length=30)),
                ('custom_name', models.CharField(blank=True, help_text="Override display name if needed e.g. 'Form 1'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='tenants.school')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text='e.g. Nkrumah, Nightingale, A, B, Science, Business', max_length=100)),
                ('elective_group', models.CharField(blank=True, choices=[('', 'None / N/A'), ('science', 'Science'), ('business', 'Business'), ('arts', 'General Arts'), ('home_economics', 'Home Economics'), ('visual_arts', 'Visual Arts'), ('technical', 'Technical'), ('agriculture', 'Agriculture')], default='', help_text='For SHS elective streams only', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.academicyear')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='tenants.branch')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.classlevel')),
                ('form_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_classes', to='tenants.schoolmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='tenants.school')),
            ],
            options={
                'ordering': ['class_level__order', 'section_name'],
                'unique_together': {('school', 'academic_year', 'class_level', 'section_name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='Short code e.g. MATH, ENG, SCI', max_length=20)),
                ('subject_type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('optional', 'Optional')], default='core', max_length=10)),
                ('elective_group', models.CharField(blank=True, choices=[('', 'None / N/A'), ('science', 'Science'), ('business', 'Business'), ('arts', 'General Arts'), ('home_economics', 'Home Economics'), ('visual_arts', 'Visual Arts'), ('technical', 'Technical'), ('agriculture', 'Agriculture')], default='', help_text='For elective subjects — which SHS stream this belongs to', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tenants.school')),
            ],
            options={
                'ordering': ['subject_type', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('academic_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.PositiveIntegerField(default=5)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_assignments', to='tenants.schoolmember')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.term')),
            ],
            options={
                'ordering': ['classroom', 'subject__name'],
                'unique_together': {('classroom', 'subject', 'term')},
            },
        ),
    ]
