# Generated by Django 6.0.2 on 2026-02-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
    ]
